# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docs CI Build

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        extended: true
    - run: npm install
      working-directory: './docs'
    - name: Build docs
      run: hugo --minify
      working-directory: './docs'
      env:
        HUGO_ENV: production
    - name: Upload docs packages
      uses: actions/upload-artifact@v1
      with:
        name: beatvortex-docs
        path: docs/public/
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/public